### ISSUE TITLE
Files not saving

### ISSUE THREAD

**Issue by aidano-7** [rand-net/khan-dl#10]
I am using Ubuntu with WSL.
I tried to download the files for multiple sources, but no files saved. To be sure this wasn't an issue with Ubuntu, I used Windows Powershell and Command Prompt. There is no error message, but there was no folder or files in the directory I was using.

**Comment by crobertsbmw** [comment]
I'm having the same issue. I tried running
`khan-dl -c "https://www.khanacademy.org/computing/computer-science"`
And I get this output:
```
Looking up https://www.khanacademy.org/computing/computer-science .....
Generating Path Slugs..... 

Downloading Videos....

['/Users/chase/Desktop/youtube-offline//Computer science/0_Algorithms/0_Intro to algorithms/0_What is an algorithm and why should you care? .mp4', '/Users/chase/Desktop/youtube-offline//Computer science/1_Cryptography/0_Ancient cryptography/0_What is cryptography? .mp4', '/Users/chase/Desktop/youtube-offline//Computer science/1_Cryptography/0_Ancient cryptography/1_The Caesar cipher .mp4', '/Users/chase/Desktop/youtube-offline//Computer science/1_Cryptography/0_Ancient cryptography/4_Polyalphabetic cipher .mp4', '/Users/chase/Desktop/youtube-offline//Computer science/1_Cryptography/0_Ancient cryptography/6_The one-....
```

**Comment by aidano-7** [comment]
Do you think it is because it saves with two slashes?
```

'/Users/chase/Desktop/youtube-offline**//**Computer science/0_Algorithms/0_Intro to algorithms/0_What is an algorithm and why should you care? .mp4

```

**Comment by rand-net** [comment]
It was a bug made on a dev branch. It fixed the bug and you can install the latest version 0.1.3

`pip install khan-dl --no-cache-dir`
