### ISSUE TITLE
Many sub folders are skipped and Videos are saved with wrong file name in wrong folder

### ISSUE THREAD

**Issue by nemoece** [rand-net/khan-dl#12]
Please check with the following command. Many sub folders are skipped and videos are getting saved with wrong filename.
khan-dl -c https://www.khanacademy.org/math/cc-1st-grade-math.

Tried to debug the problem.
            for unit_sub_heads, unit_sub_head_body in zip(
                self.unit_page_html.find_all(
                    attrs={"data-test-id": "lesson-card-link"}
                ),
                self.unit_page_html.find_all("div", class_="_1o51yl6"),
            ):

In the above line "self.unit_page_html.find_all("div", class_="_1o51yl6")" does not find all videos. Please rectify this problem. I tried. But i couldn't. I need this script asap. It would be very much helpful If you solved this issue.

**Comment by rand-net** [comment]
It seem to be issue with filtering out the quiz sections and their contents. Also some unit pages have extra videos that messes up with the naming and output of videos.

**Comment by rand-net** [comment]
Most of the videos are saved with correct file names, except a few.
