### ISSUE TITLE
Error when downloading all of Khan

### ISSUE THREAD

**Issue by cbracketdash** [rand-net/khan-dl#14]
After running ```khan-dl --all``` twice, I receive the Python error ```AttributeError: 'Khan_DL' object has no attribute 'video_topics_list'```. Both times, it errored out on video with id "8AdcPD50aTQ".

**Comment by Balaji-Ganesh** [comment]
Yes, we to got the same error when tried with the course url as given in the example :"khan-dl -c https://www.khanacademy.org/science/ap-physics-1" as well as with the another course :https://www.khanacademy.org/math/multivariable-calculus/thinking-about-multivariable-function.

Can anyone help in this issue. Is there any mistake in specifying the course_url?

**Comment by rand-net** [comment]
Fixed on 1.0.1. Install the latest release using
`pip install khan-dl -U`
