### ISSUE TITLE
AttributeError when tried to download specific lecture of the course.

### ISSUE THREAD

**Issue by Balaji-Ganesh** [rand-net/khan-dl#15]
Sir @rand-net, tried as answered in the issue-14 :  `pip install khan-dl -U`. **Thanks** for that, it worked fine for the 2nd time run.
__
But, when tried to download the specific lecture of the course, it gives the below error.`**AttributeError: 'NoneType' object has no attribute 'text'**`

More details:
`
$ khan-dl -c https://www.khanacademy.org/math/multivariable-calculus/thinking-about-multivariable-function/introduction-to-multivariable-calculus/v/multivariable-functions
 _  __ _   _     _     _   _         ____   _     
| |/ /| | | |   / \   | \ | |       |  _ \ | |    
| ' / | |_| |  / _ \  |  \| | _____ | | | || |    
| . \ |  _  | / ___ \ | |\  ||_____|| |_| || |___ 
|_|\_\|_| |_|/_/   \_\|_| \_|       |____/ |_____|
                                                  

Looking up https://www.khanacademy.org/math/multivariable-calculus/thinking-about-multivariable-function/introduction-to-multivariable-calculus/v/multivariable-functions .....
Generating Path Slugs..... 
Traceback (most recent call last):
  File "/home/krishna/.local/bin/khan-dl", line 7, in <module>
    from khan_dl.__init__ import main
  File "/home/krishna/.local/lib/python3.8/site-packages/khan_dl/__init__.py", line 50, in <module>
    khan_down.generate_unit_slugs()
  File "/home/krishna/.local/lib/python3.8/site-packages/khan_dl/khan_downloader.py", line 26, in generate_unit_slugs
    course_title = self.course_root_page_html.find(
AttributeError: 'NoneType' object has no attribute 'text'
`

**A small doubt:** _Does this library intended to designed to work also with the specific individual lectures of the course or the entire course?_

**Comment by rand-net** [comment]
This library isn't intended to download specific units of a course. You can use youtube-dl instead.
