### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by srcoulombe** [rand-net/khan-dl#21]
Installating using ` pip install -U khan-dl` and using the `khan-dl` command afterwards raises the exception:

```ModuleNotFoundError: No module named 'yt_dlp'```

A possible fix would be to include `yt-dlp` in `requirements.txt` or add `python -m  pip install -U yt-dlp` in the installation steps.

**Comment by srcoulombe** [comment]
Thanks for building this by the way! Super freakin useful!

**Comment by rand-net** [comment]
I have submitted a [PR](https://github.com/yt-dlp/yt-dlp/pull/3462) on yt-dlp repo. At the moment, yt-dlp doesn't have the fixes. Therefore including it in requirements.txt or installing it separately wouldn't fix [Issue 20](https://github.com/rand-net/khan-dl/issues/20). In the meantime, you can install yt-dlp from my fork as mentioned in the [readme](https://github.com/rand-net/khan-dl#installation).

` pip install git+https://github.com/rand-net/yt-dlp@fix-khanacademy`

**Comment by pukkandan** [comment]
FYI: Anything you can `pip install` can be put in `requirements.txt`

**Comment by rand-net** [comment]
Yeah, I know that. But I wanted it to be part of the package, as pypi doesn't allow a git dependency. Fixed in the latest release.
