### ISSUE TITLE
Not Downloading all Parts of Linear Algebra

### ISSUE THREAD

**Issue by cbracketdash** [rand-net/khan-dl#6]
I was trying to download Linear Algebra with ```python khan-dl.py -c https://www.khanacademy.org/math/linear-algebra``` but it only downloaded ```0_Vectors and spaces```. I looked on Khan Academy and it should include Matrix Transformations and Alternate Coordinate Systems.

I thought this was a problem with the -c flag so I also tried the interactive download as well. I ran ```python khan-dl -i```,  Math, Linear algebra, and I got the same result.

Any ideas on what's going on?

**Comment by cbracketdash** [comment]
It is also worth mentioning that while download AP Chemistry, it stops at 3_Electronic structure of atoms when the course also includes Periodic Table, Chemical bonds, States matter and intermolecular forces, etc.

**Comment by cbracketdash** [comment]
For those who want a workaround to this, there are Khan Academy course playlists on their youtube channel that you can download with ```youtube-dl [video/playlist link]```

Linear Algebra: https://www.youtube.com/playlist?list=PLFD0EB975BA0CC1E0

AP Chemistry: https://www.youtube.com/playlist?list=PLvrLiOD6bJ8xLXcbiOjh1krquIrd2MQTA

**Comment by rand-net** [comment]
The scraper fails to collect youtube id for the remaining videos. Currently working on to collect all the youtube ids.

**Comment by rand-net** [comment]
Fixed on version 0.1.4

`pip install khan-dl -U`
