### ISSUE TITLE
Option download all (--all) fails

### ISSUE THREAD

**Issue by alex-111-gh** [rand-net/khan-dl#8]
Trying to use command line param `--all` **FAILS** after downloading roughly 2.2Gb of courses with the following exception (raised in `youtube-dl`):

```
youtube_dl.utils.DownloadError: ERROR: Error in output template: unsupported format character 'm' (0x6d) at index 123 (encoding: 'UTF-8')
```

Workaround is not clear at this time.

**Comment by rand-net** [comment]
Could you share the video filename it failed on. It appears to be a file name issue.
